# Generated by Django 4.0.6 on 2022-07-22 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bouapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='last_updated_by',
            field=models.CharField(default='admin', max_length=20),
        ),
        migrations.AddField(
            model_name='item',
            name='last_updated_by',
            field=models.CharField(default='admin', max_length=20),
        ),
        migrations.AddField(
            model_name='person',
            name='last_updated_by',
            field=models.CharField(default='admin', max_length=20),
        ),
        migrations.AlterField(
            model_name='badge',
            name='person_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bouapp.person'),
        ),
    ]
