# Generated by Django 4.0.6 on 2022-07-26 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bouapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='status',
            field=models.CharField(choices=[('In', 'In'), ('Out', 'Out')], max_length=20),
        ),
    ]
