# Generated by Django 4.0.6 on 2022-07-22 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bouapp', '0002_badge_last_updated_by_item_last_updated_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='person_name',
            field=models.CharField(choices=[('john paul', 'JOHN PAUL'), ('Asem', 'ASEM')], max_length=20),
        ),
    ]
